### PR TITLE
v0.15

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge-admin please rerender

**Comment by thewchan** [comment]
@rr- @Chilipp  review and merge appreciated!

**Review by rr- — APPROVED** [review]

**Comment by Chilipp** [comment]
thanks @thewchan. I must admit that I did not look too much into this repo for the past couple of months and I am anyway not the core maintainer of `docstring_parser`, I just brought it to conda-forge :sweat_smile: 

@rr- is there a reason why you are just approving PRs and not merging them? Are you waiting for my feedback? Don't worry about that, you are the person who knows this package best :wink: Please do merge stuff when you think it's fine.

@thewchan just out of interest: As I did not pay attention before, I just realized that the CI in the automated MRs by the conda-forge bot (#10 and #11)  failed. I did not yet look into the details. What did you change such that your CI is passing here?

**Comment by thewchan** [comment]
@rr- @Chilipp Agreed; please merge if all test pasts and if you approve of the PR. I've added myself as a maintainer to help with this feedstock.

@Chilipp, the previous auto PR were failing because I believe upstream has switched to using Poetry as the build tool, which must be added to the `host` section of the recipe.

**Comment by Chilipp** [comment]
> @Chilipp, the previous auto PR were failing because I believe upstream has switched to using Poetry as the build tool, which must be added to the host section of the recipe.

I see, thanks for the explanation! Then I would suggest to fix #10 and #11 such that we keep the official way and have all versions available. I will fix the two PRs.

@rr- as this is your package, it's your choice to add @thewchan as a maintainer to this feedstock (I recommend to do so, he seems to be a skilled guy :wink:). If you'd like to add him, please enter the following as a stand-alone comment in a PR (in this PR for instance):

`@conda-forge-admin, please add user @thewchan`

see https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username

**Comment by thewchan** [comment]
@Chilipp that's certainly fine by me; I would have modified the auto-PRs if I have the right permission.

**Pull request closed without merging**
